-- ====================================================================================
-- INSERCIÓN DE DATOS: Tabla cargos
-- Fuente: Cargos.xlsx (Nómina Galac)
-- Dialecto: PostgreSQL (InsForge)
-- ====================================================================================

INSERT INTO cargos (codigo, nombre, descripcion, estado)
VALUES
    ('Cargo-0001', 'Analista Administrativo', 'Analista Administrativo', TRUE),
    ('Cargo-0002', 'Analista de Almacén', 'Analista de Almacén', TRUE),
    ('Cargo-0003', 'Analista de Aseguramiento de la Calidad', 'Analista de Aseguramiento de la Calidad', TRUE),
    ('Cargo-0004', 'Analista de Compras', 'Analista de Compras', TRUE),
    ('Cargo-0005', 'Analista de Control de Calidad', 'Analista de Control de Calidad', TRUE),
    ('Cargo-0006', 'Analista de Finanzas', 'Analista de Finanzas', TRUE),
    ('Cargo-0007', 'Analista de Material y Empaque', 'Analista de Material y Empaque', TRUE),
    ('Cargo-0008', 'Analista de Mercadeo', 'Analista de Mercadeo', TRUE),
    ('Cargo-0009', 'Analista de Microbiología', 'Analista de Microbiología', TRUE),
    ('Cargo-0010', 'Analista de Procesos', 'Analista de Procesos', TRUE),
    ('Cargo-0011', 'Analista de Proyectos', 'Analista de Proyectos', TRUE),
    ('Cargo-0012', 'Analista de Soporte', 'Analista de Soporte', TRUE),
    ('Cargo-0013', 'Analista de Talento Humano', 'Analista de Talento Humano', TRUE),
    ('Cargo-0014', 'Analista de Tesorería', 'Analista de Tesorería', TRUE),
    ('Cargo-0015', 'Analista de Ventas', 'Analista de Ventas', TRUE),
    ('Cargo-0016', 'Asesor de Ventas', 'Asesor de Ventas', TRUE),
    ('Cargo-0017', 'Asistente Administrativo', 'Asistente Administrativo', TRUE),
    ('Cargo-0018', 'Asistente de Control de Calidad', 'Asistente de Control de Calidad', TRUE),
    ('Cargo-0019', 'Asistente de Empaque', 'Asistente de Empaque', TRUE),
    ('Cargo-0020', 'Asistente de Mercadeo', 'Asistente de Mercadeo', TRUE),
    ('Cargo-0021', 'Asistente Integral de Materiales', 'Asistente Integral de Materiales', TRUE),
    ('Cargo-0022', 'Consultor Jurídico', 'Consultor Jurídico', TRUE),
    ('Cargo-0023', 'Coordinador Almacén Tráfico y Despacho', 'Coordinador Almacén Tráfico y Despacho', TRUE),
    ('Cargo-0024', 'Coordinador de Administración de Ventas', 'Coordinador de Administración de Ventas', TRUE),
    ('Cargo-0025', 'Coordinador de Almacén', 'Coordinador de Almacén', TRUE),
    ('Cargo-0026', 'Coordinador de Compensación y Pagos', 'Coordinador de Compensación y Pagos', TRUE),
    ('Cargo-0027', 'Coordinador de Compras', 'Coordinador de Compras', TRUE),
    ('Cargo-0028', 'Coordinador de Contabilidad e Impuestos', 'Coordinador de Contabilidad e Impuestos', TRUE),
    ('Cargo-0029', 'Coordinador de Costos', 'Coordinador de Costos', TRUE),
    ('Cargo-0030', 'Coordinador de CRM', 'Coordinador de CRM', TRUE),
    ('Cargo-0031', 'Coordinador de Cuentas por Cobrar', 'Coordinador de Cuentas por Cobrar', TRUE),
    ('Cargo-0032', 'Coordinador de Cuentas por Pagar', 'Coordinador de Cuentas por Pagar', TRUE),
    ('Cargo-0033', 'Coordinador de Elaboración', 'Coordinador de Elaboración', TRUE),
    ('Cargo-0034', 'Coordinador de Empaque', 'Coordinador de Empaque', TRUE),
    ('Cargo-0035', 'Coordinador de Innovación y Empaque', 'Coordinador de Innovación y Empaque', TRUE),
    ('Cargo-0036', 'Coordinador de Mercadeo', 'Coordinador de Mercadeo', TRUE),
    ('Cargo-0037', 'Coordinador de Microbiología', 'Coordinador de Microbiología', TRUE),
    ('Cargo-0038', 'Coordinador de Planificación', 'Coordinador de Planificación', TRUE),
    ('Cargo-0039', 'Coordinador de Procesos', 'Coordinador de Procesos', TRUE),
    ('Cargo-0040', 'Coordinador de Proyectos y Gestion Administrativa', 'Coordinador de Proyectos y Gestion Administrativa', TRUE),
    ('Cargo-0041', 'Coordinador de Servicios Generales', 'Coordinador de Servicios Generales', TRUE),
    ('Cargo-0042', 'Coordinador de Talento Humano', 'Coordinador de Talento Humano', TRUE),
    ('Cargo-0043', 'Director de Finanzas', 'Director de Finanzas', TRUE),
    ('Cargo-0044', 'Director de Ventas', 'Director de Ventas', TRUE),
    ('Cargo-0045', 'Director Técnico', 'Director Técnico', TRUE),
    ('Cargo-0046', 'Diseñador', 'Diseñador', TRUE),
    ('Cargo-0047', 'Donación', 'Donación', TRUE),
    ('Cargo-0048', 'Ejecutivo de Ventas', 'Ejecutivo de Ventas', TRUE),
    ('Cargo-0049', 'Electromecánico', 'Electromecánico', TRUE),
    ('Cargo-0050', 'Especialista de Aplicaciones', 'Especialista de Aplicaciones', TRUE),
    ('Cargo-0051', 'Especialista de Aseguramiento de la Calidad', 'Especialista de Aseguramiento de la Calidad', TRUE),
    ('Cargo-0052', 'Especialista de Compras', 'Especialista de Compras', TRUE),
    ('Cargo-0053', 'Especialista de Control de Calidad', 'Especialista de Control de Calidad', TRUE),
    ('Cargo-0054', 'Especialista de Farmacovigilancia', 'Especialista de Farmacovigilancia', TRUE),
    ('Cargo-0055', 'Especialista de Finanzas', 'Especialista de Finanzas', TRUE),
    ('Cargo-0056', 'Especialista de Inteligencia de Negocios', 'Especialista de Inteligencia de Negocios', TRUE),
    ('Cargo-0057', 'Especialista de Investigación y Desarrollo', 'Especialista de Investigación y Desarrollo', TRUE),
    ('Cargo-0058', 'Especialista de Planificación', 'Especialista de Planificación', TRUE),
    ('Cargo-0059', 'Especialista de Seguridad y Salud Laboral', 'Especialista de Seguridad y Salud Laboral', TRUE),
    ('Cargo-0060', 'Especialista de Soporte', 'Especialista de Soporte', TRUE),
    ('Cargo-0061', 'Especialista de Ventas', 'Especialista de Ventas', TRUE),
    ('Cargo-0062', 'Gerente de Almacen', 'Gerente de Almacen', TRUE),
    ('Cargo-0063', 'Gerente de Aseguramiento de la Calidad', 'Gerente de Aseguramiento de la Calidad', TRUE),
    ('Cargo-0064', 'Gerente de Compras', 'Gerente de Compras', TRUE),
    ('Cargo-0065', 'Gerente de Control de Calidad', 'Gerente de Control de Calidad', TRUE),
    ('Cargo-0066', 'Gerente de Finanzas', 'Gerente de Finanzas', TRUE),
    ('Cargo-0067', 'Gerente de Inteligencia de Negocios', 'Gerente de Inteligencia de Negocios', TRUE),
    ('Cargo-0068', 'Gerente de Mantenimiento Técnico y Servicios', 'Gerente de Mantenimiento Técnico y Servicios', TRUE),
    ('Cargo-0069', 'Gerente de Mercadeo', 'Gerente de Mercadeo', TRUE),
    ('Cargo-0070', 'Gerente de Planificación', 'Gerente de Planificación', TRUE),
    ('Cargo-0071', 'Gerente de Producción', 'Gerente de Producción', TRUE),
    ('Cargo-0072', 'Gerente de Seguridad y Salud Laboral', 'Gerente de Seguridad y Salud Laboral', TRUE),
    ('Cargo-0073', 'Gerente de Talento Humano', 'Gerente de Talento Humano', TRUE),
    ('Cargo-0074', 'Gerente de Tesorería', 'Gerente de Tesorería', TRUE),
    ('Cargo-0075', 'Gerente de Ventas', 'Gerente de Ventas', TRUE),
    ('Cargo-0076', 'Gerente de Ventas Nacional- Cuentas Claves', 'Gerente de Ventas Nacional- Cuentas Claves', TRUE),
    ('Cargo-0077', 'Inspector de Aseguramiento de la Calidad', 'Inspector de Aseguramiento de la Calidad', TRUE),
    ('Cargo-0078', 'Lider de Ventas', 'Lider de Ventas', TRUE),
    ('Cargo-0079', 'Mecánico', 'Mecánico', TRUE),
    ('Cargo-0080', 'Muestreador', 'Muestreador', TRUE),
    ('Cargo-0081', 'Operario de Almacén', 'Operario de Almacén', TRUE),
    ('Cargo-0082', 'Operario de Elaboración', 'Operario de Elaboración', TRUE),
    ('Cargo-0083', 'Operario de Pesada', 'Operario de Pesada', TRUE),
    ('Cargo-0084', 'Operario de Producción', 'Operario de Producción', TRUE),
    ('Cargo-0085', 'Operario de Servicios Generales', 'Operario de Servicios Generales', TRUE),
    ('Cargo-0086', 'Operario Integral', 'Operario Integral', TRUE),
    ('Cargo-0087', 'Operario Lider', 'Operario Lider', TRUE),
    ('Cargo-0088', 'Operario Lider de Almacen', 'Operario Lider de Almacen', TRUE),
    ('Cargo-0089', 'Pasante', 'Pasante', TRUE),
    ('Cargo-0090', 'Presidente', 'Presidente', TRUE),
    ('Cargo-0091', 'Supervisor de Elaboración', 'Supervisor de Elaboración', TRUE),
    ('Cargo-0092', 'Supervisor de Empaque', 'Supervisor de Empaque', TRUE),
    ('Cargo-0093', 'Supervisor de Mantenimiento Técnico y Servicios', 'Supervisor de Mantenimiento Técnico y Servicios', TRUE),
    ('Cargo-0094', 'Supervisor de Pesada', 'Supervisor de Pesada', TRUE),
    ('Cargo-0095', 'Vice Presidente', 'Vice Presidente', TRUE)
ON CONFLICT (codigo) DO UPDATE SET
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    estado = EXCLUDED.estado,
    updated_at = CURRENT_TIMESTAMP;
